FROM python:3.11-slim

WORKDIR /app

COPY requirements-migrate.txt .
RUN pip install --no-cache-dir -r requirements-migrate.txt

COPY alembic.ini .
COPY migrations/ ./migrations/

CMD ["alembic", "upgrade", "head"]
